[package]
name = "rustcraft"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
wgpu = { version = "30", default-features = false, features = ["std", "parking_lot", "dx12", "vulkan", "metal", "wgsl"] }
winit = "0.30"
glam = "0.29"
font8x8 = "0.3"
png = "0.17"
zip = { version = "2", default-features = false, features = ["deflate"] }
cpal = "0.15"
ab_glyph = "0.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
