//! The fishing rod and its bobber, made in Blockbench (`tools/blockbench/fishing_rod.bbmodel`,
//! generated by `gen_fishing_rod.py`): a spinning rod with a cork grip, a reel seat, a
//! spinning reel under it (its crank and rotor turn), a tapered graphite blank in segments
//! that bend progressively toward the tip, line guides getting smaller toward it, and a
//! red-and-white float. `bbmodel_to_rust.py` made the data and the texture pages.
//!
//! Model space: blocks, the rod lying along +Z from its butt at the origin (the grip where the
//! right hand holds it, `RodPoints::grip`), the reel under it with its crank on the +X side
//! (the angler's left, held right-handed: the left hand turns it), up +Y. (The Blockbench
//! model is in pixels, 16 to a block.)

#[allow(unused_imports, dead_code)]
mod data {
    include!("fishing_rod_data.rs");
}
use data::{BONES, CUBES};
pub use data::PAGES;

use super::viewmodel::{cube_matrix, emit_cube, find_bone, rot_zyx, Bone};
use crate::world::mesh::Vertex;
use crate::world::textures::tex;
use glam::{Mat4, Quat, Vec3};

/// The texture pages (`PAGES` of 128x128, one under the other), loaded into the texture
/// layers from `tex::FISHING_ROD_MODEL`.
pub static PNG: &[u8] = include_bytes!("fishing_rod.png");

/// Length of the rod (blocks), butt to tip, straight.
pub const LENGTH: f32 = 2.2;

/// Blockbench pixels to blocks.
const PX: f32 = 1.0 / 16.0;
/// Where the right hand holds the rod (model pixels): round the reel seat, the reel's stem
/// between its fingers.
const GRIP: Vec3 = Vec3::new(0.0, 0.0, 6.3);
/// The middle of the crank's knob (model pixels, in the `crank` bone, at rest pointing down).
const KNOB: Vec3 = Vec3::new(1.64, -4.2, 6.0);
/// The middle of the tip top's ring (model pixels, in the `tip` bone).
const TIP: Vec3 = Vec3::new(0.0, -0.17, 35.2);
/// How far the whole blank turns (radians, butt to tip) bent hard.
const MAX_BEND: f32 = 1.35;
/// Rotor turns per crank turn (the reel's gear ratio).
const GEAR_RATIO: f32 = 5.2;
/// The segments of the blank (`blank0`.. from the grip).
const SEGMENTS: usize = 8;

/// How the rod looks at the moment.
#[derive(Clone, Copy, Default, Debug)]
pub struct RodPose {
    /// The crank's turn (radians; reeling in turns it forward).
    pub crank: f32,
    /// How far the rod is bent by the line's pull (0 straight .. 1 bent hard), and toward
    /// where in model space (unit vector across the rod; usually down/forward to the line).
    pub bend: f32,
    pub bend_dir: Vec3,
}

/// Points of the rod where `m` puts them.
#[derive(Clone, Copy, Default, Debug)]
pub struct RodPoints {
    /// The tip, where the line leaves the rod.
    pub tip: Vec3,
    /// Where the right hand holds the grip.
    pub grip: Vec3,
    /// The crank's knob, for the left hand.
    pub crank: Vec3,
}

fn bone(name: &str) -> usize {
    find_bone(BONES, name).unwrap_or(0)
}

/// Whether bone `b` is `root` or in it.
fn under(mut b: usize, root: usize) -> bool {
    loop {
        if b == root {
            return true;
        }
        let p = BONES[b].parent;
        if p < 0 {
            return false;
        }
        b = p as usize;
    }
}

/// How much of the bend each segment of the blank takes (adding up to 1): little near the
/// grip, more and more toward the tip, like a loaded fast-action blank.
fn bend_share(i: usize) -> f32 {
    let w = |k: usize| ((k + 1) as f32).powf(1.7);
    w(i) / (0..SEGMENTS).map(w).sum::<f32>()
}

/// Each bone's transform (model pixels to where `m` puts them) in `pose`.
fn matrices(pose: &RodPose, m: Mat4) -> Vec<Mat4> {
    let crank = bone("crank");
    let rotor = bone("rotor");
    let blank0 = bone("blank0");
    // The bend: every segment turns about the same axis across the rod, toward bend_dir.
    let dir = Vec3::new(pose.bend_dir.x, pose.bend_dir.y, 0.0).normalize_or_zero();
    let axis = Vec3::Z.cross(dir).normalize_or_zero();
    let bend = pose.bend.clamp(0.0, 1.0) * MAX_BEND;
    let mut mats: Vec<Mat4> = Vec::with_capacity(BONES.len());
    for (i, b) in BONES.iter().enumerate() {
        let Bone { parent, origin, rot, .. } = *b;
        let parent = if parent < 0 { m * Mat4::from_scale(Vec3::splat(PX)) } else { mats[parent as usize] };
        let mut r = Vec3::from(rot);
        if i == crank {
            r.x += pose.crank.to_degrees();
        } else if i == rotor {
            r.z -= (pose.crank * GEAR_RATIO).to_degrees();
        }
        let mut turn = rot_zyx(r);
        if (blank0..blank0 + SEGMENTS).contains(&i) && axis != Vec3::ZERO && bend > 0.0 {
            turn = Mat4::from_quat(Quat::from_axis_angle(axis, bend * bend_share(i - blank0))) * turn;
        }
        let o = Vec3::from(origin);
        mats.push(parent * Mat4::from_translation(o) * turn * Mat4::from_translation(-o));
    }
    mats
}

/// The rod where `m` puts its model space.
pub fn emit(out: &mut Vec<Vertex>, m: Mat4, pose: &RodPose, light: [u8; 4], fl: u8) -> RodPoints {
    let mats = matrices(pose, m);
    let rod = bone("rod");
    for c in CUBES.iter().filter(|c| under(c.bone, rod)) {
        emit_cube(out, c, mats[c.bone] * cube_matrix(c), tex::FISHING_ROD_MODEL, light, fl);
    }
    RodPoints {
        tip: mats[bone("tip")].transform_point3(TIP),
        grip: mats[rod].transform_point3(GRIP),
        crank: mats[bone("crank")].transform_point3(KNOB),
    }
}

/// The rod `length` blocks long, straight, with its middle at the origin of `m` (lying about,
/// in the inventory, on a rack), still along +Z, up +Y.
#[allow(dead_code)] // (for the game: a rod lying about, on a rack)
pub fn emit_sized(out: &mut Vec<Vertex>, m: Mat4, length: f32, light: [u8; 4], fl: u8) {
    let k = length / LENGTH;
    let m = m * Mat4::from_scale(Vec3::splat(k)) * Mat4::from_translation(Vec3::new(0.0, 0.0, -LENGTH * 0.5));
    emit(out, m, &RodPose::default(), light, fl);
}

/// The bobber (floating on water with its middle at the origin of `m`, about 0.2 blocks tall),
/// the line tied to its top at `m`'s (0, 0.1, 0).
pub fn emit_bobber(out: &mut Vec<Vertex>, m: Mat4, light: [u8; 4], fl: u8) {
    let root = bone("bobber");
    let m = m * Mat4::from_scale(Vec3::splat(PX));
    for c in CUBES.iter().filter(|c| under(c.bone, root)) {
        emit_cube(out, c, m * cube_matrix(c), tex::FISHING_ROD_MODEL, light, fl);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn points(pose: RodPose) -> RodPoints {
        emit(&mut Vec::new(), Mat4::IDENTITY, &pose, [0; 4], 0)
    }

    #[test]
    fn the_tip_is_at_the_end_and_bends_toward_the_pull() {
        let straight = points(RodPose::default());
        assert!((straight.tip.length() - LENGTH).abs() < 0.02, "{}", straight.tip);
        assert!(straight.tip.z > LENGTH - 0.01);
        // The hand on the grip, the reel's knob under the rod on the +X side (the left hand's).
        assert!(straight.grip.z > 0.2 && straight.grip.z < 0.6 && straight.grip.y.abs() < 0.05);
        assert!(straight.crank.x > 0.05 && straight.crank.y < -0.15, "{}", straight.crank);
        for dir in [Vec3::NEG_Y, Vec3::X, Vec3::new(0.6, -0.8, 0.0)] {
            let mut last = straight.tip;
            for bend in [0.25, 0.5, 1.0] {
                let p = points(RodPose { bend, bend_dir: dir, ..RodPose::default() });
                // Further toward the pull, nearer the butt; the blank does not stretch much.
                assert!((p.tip - last).dot(dir) > 0.05, "{bend} {dir}: {} -> {}", last, p.tip);
                assert!(p.tip.z < last.z);
                assert!(p.tip.length() < LENGTH + 0.01 && p.tip.length() > LENGTH * 0.75);
                // The grip does not move.
                assert!(p.grip.distance(straight.grip) < 1e-5);
                last = p.tip;
            }
            // Bent hard, the tip points well down toward the pull.
            assert!(last.dot(dir) > 0.6, "{last}");
        }
    }

    #[test]
    fn the_knob_goes_round_the_reel() {
        let at = |crank: f32| points(RodPose { crank, ..RodPose::default() }).crank;
        let (a, b, c) = (at(0.0), at(std::f32::consts::FRAC_PI_2), at(std::f32::consts::PI));
        // Round an axis along X: x stays, it goes forward first (reeling in), then up.
        assert!((a.x - b.x).abs() < 1e-4 && (a.x - c.x).abs() < 1e-4);
        let centre = (a + c) * 0.5;
        assert!((a.distance(centre) - b.distance(centre)).abs() < 1e-3);
        assert!(a.distance(centre) > 0.08, "{a} {centre}");
        assert!(c.y > a.y + 0.15);
        assert!(at(0.3).z < a.z, "the bottom of the turn moves back");
        assert!(at(0.0).distance(at(std::f32::consts::TAU)) < 1e-4);
    }

    #[test]
    fn the_bobber_is_about_a_fifth_of_a_block() {
        let mut out = Vec::new();
        emit_bobber(&mut out, Mat4::IDENTITY, [0; 4], 0);
        let (lo, hi) = out.iter().fold((f32::MAX, f32::MIN), |(lo, hi), v| (lo.min(v.pos[1]), hi.max(v.pos[1])));
        assert!((hi - 0.1).abs() < 0.01 && (lo + 0.1).abs() < 0.01, "{lo}..{hi}");
        let mut rod = Vec::new();
        emit(&mut rod, Mat4::IDENTITY, &RodPose::default(), [0; 4], 0);
        assert!(!rod.is_empty() && rod.iter().all(|v| v.pos[2] > -0.05));
    }
}
