// Generated by tools/blockbench/bbmodel_to_rust.py from tools/blockbench/tp_ak.bbmodel.
// Do not edit: change the model in Blockbench and run the script again.
use crate::model::viewmodel::{Anim, Bone, Channel, Cube, Face, Key};

/// Texture pages (128x128 layers) in `tp_ak.png`, from top to bottom.
pub const PAGES: u32 = 1;

pub static BONES: &[Bone] = &[
    Bone { name: "player", parent: -1, origin: [0.0, 0.0, 0.0], rot: [0.0, 0.0, 0.0] },
    Bone { name: "right_arm", parent: 0, origin: [5.0, 22.0, 0.0], rot: [0.0, 0.0, 0.0] },
    Bone { name: "left_arm", parent: 0, origin: [-5.0, 22.0, 0.0], rot: [0.0, 0.0, 0.0] },
    Bone { name: "gun", parent: 0, origin: [3.2526, 20.0495, -4.4664], rot: [0.0, 0.0, 0.0] },
    Bone { name: "left_hand", parent: 3, origin: [2.9526, 18.951, -10.7945], rot: [0.0, 0.0, 0.0] },
    Bone { name: "torso", parent: 0, origin: [0.0, 12.0, 0.0], rot: [0.0, 0.0, 0.0] },
];

pub static CUBES: &[Cube] = &[
];


pub static ANIMS: &[Anim] = &[
    Anim { name: "idle", length: 3.0, looping: 2, channels: &[
        Channel { bone: 3, kind: 0, keys: &[Key { t: 0.0, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 1.5, v: [-0.0, 0.18, 0.0], interp: 1 }, Key { t: 3.0, v: [-0.0, 0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 3, kind: 1, keys: &[Key { t: 0.0, v: [-30.0, -0.0, 0.0], interp: 1 }, Key { t: 1.5, v: [-28.5, -0.0, 0.0], interp: 1 }, Key { t: 3.0, v: [-30.0, -0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 5, kind: 1, keys: &[Key { t: 0.0, v: [-0.0, -40.0, 0.0], interp: 1 }, Key { t: 3.0, v: [-0.0, -40.0, 0.0], interp: 1 }] }, // torso
        Channel { bone: 1, kind: 1, keys: &[Key { t: 0.0, v: [67.869, 21.367, 0.0], interp: 0 }, Key { t: 1.5, v: [69.738, 21.367, 0.0], interp: 0 }, Key { t: 3.0, v: [67.869, 21.367, 0.0], interp: 0 }] }, // right_arm
        Channel { bone: 2, kind: 1, keys: &[Key { t: 0.0, v: [63.7693, -40.2397, 0.0], interp: 0 }, Key { t: 1.5, v: [65.0877, -39.923, 0.0], interp: 0 }, Key { t: 3.0, v: [63.7693, -40.2397, 0.0], interp: 0 }] }, // left_arm
    ] },
    Anim { name: "walk", length: 1.0, looping: 2, channels: &[
        Channel { bone: 3, kind: 0, keys: &[Key { t: 0.0, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 0.25, v: [0.35, -0.45, 0.0], interp: 1 }, Key { t: 0.5, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 0.75, v: [-0.35, -0.45, 0.0], interp: 1 }, Key { t: 1.0, v: [-0.0, 0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 3, kind: 1, keys: &[Key { t: 0.0, v: [-0.0, -0.0, 0.0], interp: 1 }, Key { t: 0.25, v: [-2.0, -0.0, -2.5], interp: 1 }, Key { t: 0.5, v: [-0.0, -0.0, 0.0], interp: 1 }, Key { t: 0.75, v: [-2.0, -0.0, 2.5], interp: 1 }, Key { t: 1.0, v: [-0.0, -0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 1, kind: 1, keys: &[Key { t: 0.0, v: [67.869, 21.367, 0.0], interp: 0 }, Key { t: 0.25, v: [62.845, 17.3733, 0.0], interp: 0 }, Key { t: 0.5, v: [67.869, 21.367, 0.0], interp: 0 }, Key { t: 0.75, v: [64.0577, 25.1545, 0.0], interp: 0 }, Key { t: 1.0, v: [67.869, 21.367, 0.0], interp: 0 }] }, // right_arm
        Channel { bone: 2, kind: 1, keys: &[Key { t: 0.0, v: [77.1884, -36.3802, 0.0], interp: 0 }, Key { t: 0.25, v: [74.7078, -37.4828, 0.0], interp: 0 }, Key { t: 0.5, v: [77.1884, -36.3802, 0.0], interp: 0 }, Key { t: 0.75, v: [74.2192, -35.4678, 0.0], interp: 0 }, Key { t: 1.0, v: [77.1884, -36.3802, 0.0], interp: 0 }] }, // left_arm
    ] },
    Anim { name: "sprint", length: 0.5, looping: 2, channels: &[
        Channel { bone: 3, kind: 0, keys: &[Key { t: 0.0, v: [-1.7526, -3.5495, -1.0336], interp: 1 }, Key { t: 0.125, v: [-1.4526, -4.0495, -1.0336], interp: 1 }, Key { t: 0.25, v: [-1.7526, -3.5495, -1.0336], interp: 1 }, Key { t: 0.375, v: [-2.0526, -4.0495, -1.0336], interp: 1 }, Key { t: 0.5, v: [-1.7526, -3.5495, -1.0336], interp: 1 }] }, // gun
        Channel { bone: 3, kind: 1, keys: &[Key { t: 0.0, v: [65.0, 50.0, 0.0], interp: 1 }, Key { t: 0.25, v: [62.0, 50.0, 0.0], interp: 1 }, Key { t: 0.5, v: [65.0, 50.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 5, kind: 1, keys: &[Key { t: 0.0, v: [-0.0, 30.0, 0.0], interp: 1 }, Key { t: 0.5, v: [-0.0, 30.0, 0.0], interp: 1 }] }, // torso
        Channel { bone: 1, kind: 1, keys: &[Key { t: 0.0, v: [49.8472, 32.4716, 0.0], interp: 0 }, Key { t: 0.125, v: [46.6829, 30.192, 0.0], interp: 0 }, Key { t: 0.25, v: [49.8472, 32.4716, 0.0], interp: 0 }, Key { t: 0.375, v: [48.0915, 34.6413, 0.0], interp: 0 }, Key { t: 0.5, v: [49.8472, 32.4716, 0.0], interp: 0 }] }, // right_arm
        Channel { bone: 2, kind: 1, keys: &[Key { t: 0.0, v: [88.4366, -24.618, 0.0], interp: 0 }, Key { t: 0.125, v: [84.4786, -25.5618, 0.0], interp: 0 }, Key { t: 0.25, v: [87.1042, -22.8508, 0.0], interp: 0 }, Key { t: 0.375, v: [84.3194, -21.8286, 0.0], interp: 0 }, Key { t: 0.5, v: [88.4366, -24.618, 0.0], interp: 0 }] }, // left_arm
    ] },
    Anim { name: "crouch", length: 1.0, looping: 1, channels: &[
        Channel { bone: 3, kind: 0, keys: &[Key { t: 0.0, v: [-0.0, -3.2, 1.0], interp: 1 }, Key { t: 1.0, v: [-0.0, -3.2, 1.0], interp: 1 }] }, // gun
        Channel { bone: 3, kind: 1, keys: &[Key { t: 0.0, v: [4.0, -0.0, 0.0], interp: 1 }, Key { t: 1.0, v: [4.0, -0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 1, kind: 1, keys: &[Key { t: 0.0, v: [37.0053, 26.7525, 0.0], interp: 0 }, Key { t: 1.0, v: [37.0053, 26.7525, 0.0], interp: 0 }] }, // right_arm
        Channel { bone: 2, kind: 1, keys: &[Key { t: 0.0, v: [65.3744, -38.9003, 0.0], interp: 0 }, Key { t: 1.0, v: [65.3744, -38.9003, 0.0], interp: 0 }] }, // left_arm
    ] },
    Anim { name: "aim", length: 0.3, looping: 1, channels: &[
        Channel { bone: 3, kind: 0, keys: &[Key { t: 0.0, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 0.3, v: [0.0, 2.584, -0.996], interp: 1 }] }, // gun
        Channel { bone: 3, kind: 1, keys: &[Key { t: 0.0, v: [-0.0, -0.0, 0.0], interp: 1 }, Key { t: 0.3, v: [30.0, -0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 5, kind: 1, keys: &[Key { t: 0.0, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 0.3, v: [-0.0, 0.0, 0.0], interp: 1 }] }, // torso
        Channel { bone: 1, kind: 1, keys: &[Key { t: 0.0, v: [67.869, 21.367, 0.0], interp: 0 }, Key { t: 0.3, v: [96.3033, 17.7393, 0.0], interp: 0 }] }, // right_arm
        Channel { bone: 2, kind: 1, keys: &[Key { t: 0.0, v: [77.1884, -36.3802, 0.0], interp: 0 }, Key { t: 0.3, v: [101.5114, -34.6839, 0.0], interp: 0 }] }, // left_arm
    ] },
    Anim { name: "shoot", length: 0.3, looping: 0, channels: &[
        Channel { bone: 3, kind: 0, keys: &[Key { t: 0.0, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 0.03, v: [-0.0, 0.3, 0.9], interp: 1 }, Key { t: 0.3, v: [-0.0, 0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 3, kind: 1, keys: &[Key { t: 0.0, v: [-0.0, -0.0, 0.0], interp: 1 }, Key { t: 0.03, v: [7.0, -0.0, 0.0], interp: 1 }, Key { t: 0.3, v: [-0.0, -0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 1, kind: 1, keys: &[Key { t: 0.0, v: [67.869, 21.367, 0.0], interp: 0 }, Key { t: 0.03, v: [67.4328, 26.1031, 0.0], interp: 0 }, Key { t: 0.3, v: [67.869, 21.367, 0.0], interp: 0 }] }, // right_arm
        Channel { bone: 2, kind: 1, keys: &[Key { t: 0.0, v: [77.1884, -36.3802, 0.0], interp: 0 }, Key { t: 0.03, v: [81.2265, -38.5465, 0.0], interp: 0 }, Key { t: 0.3, v: [77.1884, -36.3802, 0.0], interp: 0 }] }, // left_arm
    ] },
    Anim { name: "reload", length: 2.0, looping: 0, channels: &[
        Channel { bone: 3, kind: 0, keys: &[Key { t: 0.0, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 0.3, v: [-1.2, 2.0, 1.2], interp: 1 }, Key { t: 1.25, v: [-1.2, 2.0, 1.2], interp: 1 }, Key { t: 1.45, v: [-0.48, 0.8, 0.48], interp: 1 }, Key { t: 1.75, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 2.0, v: [-0.0, 0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 3, kind: 1, keys: &[Key { t: 0.0, v: [-0.0, -0.0, 0.0], interp: 1 }, Key { t: 0.3, v: [8.0, -0.0, 32.0], interp: 1 }, Key { t: 1.25, v: [8.0, -0.0, 32.0], interp: 1 }, Key { t: 1.45, v: [2.8, 0.0, 11.2], interp: 1 }, Key { t: 1.75, v: [-0.0, -0.0, 0.0], interp: 1 }, Key { t: 2.0, v: [-0.0, -0.0, 0.0], interp: 1 }] }, // gun
        Channel { bone: 4, kind: 0, keys: &[Key { t: 0.0, v: [-0.0, 0.0, 0.0], interp: 1 }, Key { t: 0.2, v: [-0.3523, -0.9326, 3.0593], interp: 1 }, Key { t: 0.35, v: [-0.3523, -0.9326, 3.0593], interp: 1 }, Key { t: 0.6, v: [-0.3523, -6.4326, 4.2593], interp: 1 }, Key { t: 0.8, v: [-3.3523, -8.1326, 6.7593], interp: 1 }, Key { t: 1.1, v: [-0.3523, -1.5326, 3.0593], interp: 1 }, Key { t: 1.22, v: [-0.3523, -0.9326, 3.0593], interp: 1 }, Key { t: 1.32, v: [0.2977, 2.5674, 3.7593], interp: 1 }, Key { t: 1.45, v: [0.2977, 2.5674, 4.3593], interp: 1 }, Key { t: 1.55, v: [0.2977, 2.5674, 5.4593], interp: 1 }, Key { t: 1.62, v: [0.2977, 3.3674, 5.4593], interp: 1 }, Key { t: 2.0, v: [-0.0, 0.0, 0.0], interp: 1 }] }, // left_hand
        Channel { bone: 1, kind: 1, keys: &[Key { t: 0.0, v: [67.869, 21.367, 0.0], interp: 0 }, Key { t: 0.2, v: [82.1294, 34.7914, 0.0], interp: 0 }, Key { t: 0.3, v: [90.6446, 42.0612, 0.0], interp: 0 }, Key { t: 0.35, v: [90.6446, 42.0612, 0.0], interp: 0 }, Key { t: 0.6, v: [90.6446, 42.0612, 0.0], interp: 0 }, Key { t: 0.8, v: [90.6446, 42.0612, 0.0], interp: 0 }, Key { t: 1.1, v: [90.6446, 42.0612, 0.0], interp: 0 }, Key { t: 1.22, v: [90.6446, 42.0612, 0.0], interp: 0 }, Key { t: 1.25, v: [90.6446, 42.0612, 0.0], interp: 0 }, Key { t: 1.32, v: [85.2216, 37.4553, 0.0], interp: 0 }, Key { t: 1.45, v: [75.8589, 29.1943, 0.0], interp: 0 }, Key { t: 1.55, v: [72.9927, 26.5009, 0.0], interp: 0 }, Key { t: 1.62, v: [71.1055, 24.664, 0.0], interp: 0 }, Key { t: 1.75, v: [67.869, 21.367, 0.0], interp: 0 }, Key { t: 2.0, v: [67.869, 21.367, 0.0], interp: 0 }] }, // right_arm
        Channel { bone: 2, kind: 1, keys: &[Key { t: 0.0, v: [77.1884, -36.3802, 0.0], interp: 0 }, Key { t: 0.2, v: [76.6085, -46.4158, 0.0], interp: 0 }, Key { t: 0.3, v: [80.806, -47.1842, 0.0], interp: 0 }, Key { t: 0.35, v: [80.806, -47.1842, 0.0], interp: 0 }, Key { t: 0.6, v: [62.223, -58.2901, 0.0], interp: 0 }, Key { t: 0.8, v: [45.17, -64.9679, 0.0], interp: 0 }, Key { t: 1.1, v: [78.3405, -48.036, 0.0], interp: 0 }, Key { t: 1.22, v: [80.806, -47.1842, 0.0], interp: 0 }, Key { t: 1.25, v: [86.0398, -47.2336, 0.0], interp: 0 }, Key { t: 1.32, v: [97.7664, -48.0342, 0.0], interp: 0 }, Key { t: 1.45, v: [92.305, -51.7746, 0.0], interp: 0 }, Key { t: 1.55, v: [90.4128, -57.2972, 0.0], interp: 0 }, Key { t: 1.62, v: [94.1268, -57.0933, 0.0], interp: 0 }, Key { t: 1.75, v: [85.6168, -48.5249, 0.0], interp: 0 }, Key { t: 2.0, v: [77.1884, -36.3802, 0.0], interp: 0 }] }, // left_arm
    ] },
];
